name: E2E

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Cancel any in progress run of the workflow for a given PR
# This avoids building outdated code
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  e2e-android:
    # Uncomment this to run on standard GitHub Actions runners
    # runs-on: ubuntu-latest
    runs-on:
      - nscloud-ubuntu-22.04-amd64-16x64-with-cache
      - nscloud-cache-size-20gb
      - nscloud-cache-tag-beefy-e2e-android
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        id: setup-node
        with:
          node-version-file: "package.json"
          check-latest: true
      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - run: yarn install
      - run: eas build --platform android --profile e2e --local

  e2e-ios:
    # Uncomment this to run on standard GitHub Actions runners
    # runs-on: macos-14
    runs-on: ios-e2e-group
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        id: setup-node
        with:
          node-version-file: "package.json"
          check-latest: true
      - run: brew install fastlane cocoapods
      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - run: yarn install
      - run: eas build --platform ios --profile e2e --local
